Sprint 1 step 1
f2rtQ7v/react-burger pull request #1
Opened 2024-12-15 05:37 UTC by f2rtQ7v

2024-12-15 07:03 UTC, SergeyK2004 requested changes
Здравствуйте. 

Вы проделали большую работу, что мне понравилось:

Хорошо выполнена верстка
Тип ингредиента вынесен в отдельный файл, чтобы не дублировать его в разных компонентах

но есть некоторые недочеты:

* В настоящее время вы еще не проходили TS, поэтому на данном этапе расширеня ваших файлов должно быть jsx.
* Необходимо в конструкторе отобразить ингредиенты.
* В правом верхнем углу картинки ингредиента должно отображаться количество использованных в конструкторе ингредиентов. Для данного этапа можете отображать просто 1 в каждом ингредиенте.
* Нужно посмотреть все компоненты и типизировать их пропсы, если где-то пропустили.
* https://disk.yandex.ru/d/0fO4-N9_xYt6Bg Обратите внимание на отображение неактивных пунктов меню.

Доработайте верстку главной страницы и добавьте ингредиенты в конструктор. После исправления всех недочетов, присылайте работу на повторную проверку.

2024-12-15 09:09 UTC, f2rtQ7v commented on src/components/app/app.tsx
> +  const delIngredient = useCallback(id => {
Сделано, чтобы не заниматься глупостями типа "отображать просто 1 в каждом ингредиенте". Двойной клик по ингредиенту - добавляется в конструктор, там пересчитывается сумма, а в списке ингредиентов повляется счётчик.

2024-12-16 01:40 UTC, SergeyK2004 commented on src/components/app-header/app-header.jsx
> +          <Link key={id} className={styles[id]} disabled={disabled}>
Пока еще ссылки не работают, но впоследствии вы это исправите. Обратите внимание на то, что для навигационного меню следует использовать компонент NavLink

2024-12-16 01:44 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor-item-props.js
> +
Не стоит выносить функции из компонента. Они не являются утилитарными для всего приложения и необходимы компоненту.

2024-12-16 02:34 UTC, merged