Sprint 1 step 2
f2rtQ7v/react-burger pull request #2
Opened 2024-12-17 22:38 UTC by f2rtQ7v

2024-12-18 04:38 UTC, SergeyK2004 requested changes
Здравствуйте, Виктор.

Отлично выполнена верстка. Все компоненты в модальных окнах отборажаются в соответствии с макетом. Данные загружаются с сервера. Здорово, что отображается прелодер во время обмена данными с сервером. 
Посмотрите в коде комментарии. Необходимо исправить компонент App. Буду ждать вашу работу на следующую проверку.

Что можно улучшить:

Посмотрите на отображение ингредиентов в конструкторе. Можно уже сейчас добавить им иконку для перетаскивания. Вы будете реализовывать его в следующих спринтах. https://disk.yandex.ru/d/UZ6n8REZp2r05g

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +    setTimeout(() => {
Искусственно задерживать выполнение кода не нужно. У вас и так реальный запрос на сервер выполняется. При необходимости проверки работы прелоадера, изменяйте скорость интернета в панели инструментов https://disk.yandex.ru/d/2dWFiBXaTbKiBg

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +  if (status === 'success') {
Виктор, смотрите, нам нужно использовать декларативный подход. Необходимо описать разметку с использованием внутри нее реактивных переменных (стэйтов), в зависимости от значений стэйтов разметка будет изменяться. 
Хук useEffect не должен генерировать вам разметку, это некорректно. Хук должен только один раз загрузить вам данные. При получении данных вы сохраняете их в стэйт и меняете состояние в другом стэйте с "закгрузка" на "данные получены".
А в разметке используете стэйт состояния загрузки, например в условной конструкции для отображения разной разметки.

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +  useEffect(() => {
Надо исправить:
Укажите для хука массив зависимостей, чтобы он не перевыполнялся при каждом ререндере компонента.

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +        .then(r => r.json())
**Надо исправить:**

Любой ответ от сервера нужно проверять на `ok` (на корректность) и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.

```jsx
.then(res => {
                if (res.ok) {
                    return res.json();
                }
                return Promise.reject(`Ошибка ${res.status}`);
            })
```

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/modal/modal.jsx
> +    return () => document.removeEventListener('keydown', onKeydown);
Хорошо, что удаляете слушатель при демонтировании компонента.

2024-12-18 04:38 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const [ showOrder, setShowOrder ] = useState(false);
Можно лучше

Если интересно, можно создать кастомный хук для управления модальным окном:

```jsx
import { useState, useCallback } from "react";

// кастомные хуки всегда должны начинаться с глагола `use`, чтобы реакт понял, что это хук. Он следит за их вызовами
export const useModal = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  // `useCallback` нужен для того, чтобы зафиксировать ссылку на функцию. Таким образом уменьшится кол-во перерисовок компонента, куда будет передана эта функция
  const openModal = useCallback(() => {
    setIsModalOpen(true);
  }, []);

  const closeModal = useCallback(() => {
    setIsModalOpen(false);
  }, []);

  return {
    isModalOpen,
    openModal,
    closeModal,
  };
};
```

Этот код помещают в отдельный файл useModal.js в папке hooks и импортируют функцию туда, где нужно создать показатели открытости/закрытости попапа (у каждого попапа они свои)

И теперь нужно просто вызывать хук в том компоненте, где нужно управлять попапом. Всего одна строчка кода будет (под каждый попап своя):

```jsx
  const { isModalOpen, openModal, closeModal } = useModal();
```

2024-12-18 10:24 UTC, f2rtQ7v commented on src/components/app/app.jsx
> +  if (status === 'success') {
> Хук useEffect не должен генерировать вам разметку

Он и не генерирует.

2024-12-18 10:24 UTC, f2rtQ7v commented on src/components/app/app.jsx
> +  useEffect(() => {
Не вижу, что тут требует исправлений - массив зависимостей указан.

2024-12-20 03:36 UTC, SergeyK2004 approved these changes
Все критические недочеты устранены. Ваша работа принята. Желаю успехов в дальнейшем обучении.

2024-12-20 03:36 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +  useEffect(() => {
Виктор, смотрите, у вас сейчас в массиве зависимостей указан status, который изменяется внутри самого хука.
Получается, что хук меняет свою же собственную заисимость и перевыполняется. 
Вам нужно, чтобы запрос ингредиентов происходил только один раз при загрузке приложения (при монтировании компонента)
Для этого необходимо указать **пустой** массив зависимостей.

2024-12-20 06:39 UTC, merged